# Generated by Django 3.2.6 on 2021-08-24 16:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_receita'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.receita_image_file_path),
        ),
    ]
